name: Self-Hosted Runner 

on:
  workflow_dispatch:

jobs:
  runner-job:
    runs-on: self-hosted
    steps:
      - name: Hostname
        run: hostname
      - name: Working Directory
        run: pwd
      - name: Create File
        run: |
          echo "Hello from my self-hosted" > myfile.txt
      - name: Verify File
        run: ls -l
